version: '3.9'
services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
    command: gunicorn --bind 0.0.0.0:5000 app:app

  test:
    build: .
    volumes: 
      - .:/app
    command: bash -c "python3 init_db.py && pytest"